### ISSUE TITLE
Is filecoin still actively developed ?

### ISSUE THREAD

**Issue by aronayne** [mappum/filecoin-whitepaper#1]
Hi @mappum 

Is filecoin still actively developed ? Homepage http://filecoin.io/ is avaialble. The whitepaper has not been updated in 2 years and there have been no contributions to filecoin repo (https://github.com/filecoin) in past year. Suggests this project has stalled ?

**Comment by mappum** [comment]
This filecoin whitepaper is not associated with http://filecoin.io, and neither are associated with https://github.com/filecoin, these are 3 different projects names _filecoin_. The http://filecoin.io one is still active, and you can see the teams progress on the [IPFS](https://ipfs.io/) project.

**Comment by aronayne** [comment]
Hi @mappum the whitepaper I refer to is http://filecoin.io/filecoin.pdf and is accessible from http://filecoin.io and so this whitepaper is associated with filecoin. 

"The http://filecoin.io one is still active, and you can see the teams progress on the IPFS project." so filecoin and ipfs are one project? This is confusing as there are two distinct sites 1.https://ipfs.io/ 2.http://filecoin.io but you state filecoin activity is encapsulated with IPFS github activity ?

https://github.com/ipfs/faq/issues/68 sheds a little more light on this.

**Comment by Methodise** [comment]
SIA is worth looking at, as first to market in incentivised decentralised storage. http://sia.tech

**Comment by earonesty** [comment]
Unfortunately, SIA doesn't support a distributed Javascript REST api to the SIA nodes.... so you can host websites on it.
